### Create User
POST http://localhost:3000/v1/users
Content-Type: application/json

{
    "id": "eb4c9fe2-5ba3-4877-887a-6089b2958c98",
    "fullname": "Pedro Dominguez",
    "email": "per@gmail.com",
    "image": "foto.jpg",
    "password": "Jaime123",
    "roles": [{"id": "35e7731b-1862-4982-afc0-d7f64e26f1f4"}],
    "address": {
        "street": "Sotomayor",
        "number": 525,
        "city": "Chillán",
        "country": "Chile"
    }
}

### List users
GET http://localhost:3000/v1/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmdWxsbmFtZSI6IkphaW1lIERvbWluZ3VleiIsInJvbGVzIjpbeyJpZCI6IjI3YjhiZGYyLTFjY2QtNDhlYS04NDQ3LTBlYWJjNzVjNWIyNiIsIm5hbWUiOiJURUFDSEVSIn0seyJpZCI6IjM1ZTc3MzFiLTE4NjItNDk4Mi1hZmMwLWQ3ZjY0ZTI2ZjFmNCIsIm5hbWUiOiJBRE1JTiJ9XSwiZW1haWwiOiJqYWltZUBnbWFpbC5jb20iLCJpbWFnZSI6ImZvdG8uanBnIiwiaWF0IjoxNzMxOTcxMjg1LCJleHAiOjE3MzE5NzE1ODV9.DWGbvB-O6P3cszKx1stiF_3uwjYoaeakAMEgzYWviUI

### Get user by id
GET http://localhost:3000/v1/users/9c7b7484-faea-4f84-afae-87b6d7f2e008
Content-Type: application/json
